# Generated by Django 5.0.1 on 2024-02-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='premium',
            new_name='is_premium',
        ),
    ]
